name: OWASP Dependency-Check

on:
  push:
    branches: [ "main" ]


jobs:
  depcheck:
    name: Scan dependencies with OWASP Dependency-Check
    runs-on: ubuntu-latest

    steps:
      # 1) Récupérer le code
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Node pour installer les deps (OBLIGATOIRE avant le scan)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install NPM dependencies
        # ci d'abord si package-lock.json existe, sinon install
        run: npm ci || npm install --production --unsafe-perm

      # 3) Java requis par le scanner Dependency-Check
      - name: Set up Java (required by Dependency-Check)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # 4) Lancer OWASP Dependency-Check
      #   - 'path' = le dossier à analyser (ici le repo)
      #   - 'out'  = dossier où seront produits les rapports
      #   - 'format' = types de rapports (HTML + JSON)
      #   - 'failOnCVSS' = 0 pour ne pas échouer le job si des CVE sont trouvées
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@v4
        with:
          project: cd
          path: .
          out: reports
          format: 'HTML,JSON'
          failOnCVSS: '0'

      # 5) Archiver les rapports en artefacts téléchargeables
      - name: Archive dependency check reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports
