name: Build and Analyze SBOM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate-sbom:
    name: Generate SBOM and Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install NPM dependencies
        run: npm install

      - name: Generate SBOM for JavaScript project
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          artifact-name: sbom-node-js.json

      - name: Build Docker image
        run: docker build -t my-node-app:latest .

      - name: Generate SBOM for Docker image
        uses: anchore/sbom-action@v0
        with:
          image: my-node-app:latest
          format: spdx-json
          artifact-name: sbom-docker-image.json

      - name: Upload SBOMs
        uses: actions/upload-artifact@v4
        with:
          name: sbom-artifacts
          path: |
            sbom-node-js.json
            sbom-docker-image.json
